# json configs
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/model/{{}}.dart': 'lib/generated/model/{{}}.g.dart'
