# json configs
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/model/{{}}.dart': 'lib/generated/model/{{}}.g.dart'
