using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NikkeEinkk.Components.Models.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Squad
    {
        Unknown = -1,
        None = 0,
        Counters = 1,
        Absolute = 2,
        Scouting = 3,
        InfinityRail = 4,
        External = 5,
        RecallRelease = 6,
        Matis = 7,
        CafeSweety = 8,
        Triangle = 9,
        Talentum = 10,
        LittleCannon = 11,
        Protocol = 12,
        Unlimited = 13,
        ACPU = 14,
        MightyTools = 15,
        MasterHand = 16,
        SiegePerilous = 17,
        Seraphim = 18,
        Wardress = 19,
        MaidForYou = 20,
        Exotic = 21,
        LifeTonic = 22,
        Pioneer = 23,
        Inherit = 24,
        TheClown = 25,
        [JsonProperty("777")]
        _777 = 26,
        UnderworldQueen = 27,
        MMR = 28,
        Replace = 29,
        Humanity = 30,
        Company = 31,
        EventHero01 = 32,
        EventHero02 = 33,
        EventHero03 = 34,
        Archive = 35,
        Weissritter = 36,
        HeavyGram = 37,
        HappyZoo = 38,
        RealKindness = 39,
        Heretic = 40,
        A_F_F_ = 41,
        EnikkChild = 42,
        Aegis = 43,
        BotanicGarden = 44,
        PrimaDonna = 45,
        SchoolCircle = 46,
        Ce_01 = 47,
        Overseer = 48,
        Ce002_01 = 49,
        Ce002_02 = 50,
        Akademeia = 51,
        DazzlingPearl = 52,
        Goddess = 53,
        ElectricShock = 54,
        CE003 = 55,
        Rewind = 56,
        CE004 = 57,
        BestSeller = 58,
        OldTales = 59,
        CE005 = 60,
        CookingOil = 61,
        Incubator = 62,
        CE006_01 = 63,
        CE006_02 = 64,
        CE006_03 = 65,
        OverTheHorizon = 66,
        CE007 = 67
    }
}
