using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NikkeEinkk.Components.Models.Enums
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PreferTarget
    {
        Unknown = -1,
        None = 0,
        Attacker = 1,
        Defender = 2,
        Supporter = 3,
        AttackerRandom = 4,
        DefenderRandom = 5,
        SupporterRandom = 6,
        Front = 7,
        Back = 8,
        Left = 9,
        Right = 10,
        LowHP = 11,
        HighHP = 12,
        HighMaxHP = 13,
        LowDefence = 14,
        HighDefence = 15,
        LowAttack = 16,
        HighAttack = 17,
        LowHPLastSelf = 18,
        HighHPLastSelf = 19,
        LowDefenceLastSelf = 20,
        HighDefenceLastSelf = 21,
        LowAttackLastSelf = 22,
        HighAttackLastSelf = 23,
        TargetSR = 24,
        TargetAR = 25,
        TargetAS = 26,
        TargetRL = 27,
        TargetGL = 28,
        TargetPS = 29,
        BurstStep = 30,
        Random = 31,
        LowHPFirstSelf = 32,
        HighHPFirstSelf = 33,
        LowDefenceFirstSelf = 34,
        HighDefenceFirstSelf = 35,
        LowAttackFirstSelf = 36,
        HighAttackFirstSelf = 37,
        NearbyAllyTarget = 38,
        NearbyEnemyTarget = 39,
        NearbyAllyLastSelf = 40,
        Fire = 41,
        Water = 42,
        Wind = 43,
        Electronic = 44,
        Iron = 45,
        NotStun = 46,
        LowHPCover = 47,
        LowHPRatio = 48,
        HighHPRatio = 49,
        LowMaxHP = 50,
        HaveDebuff = 51,
        HaveBuff = 52,
        NearAim = 53,
        LongInitChargeTime = 54
    }
}
