using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NikkeEinkk.Components.Models.Enums;

[JsonConverter(typeof(StringEnumConverter))]
public enum StatusTriggerType
{
    Unknown = -1,
    None = 0,
    IsAmmoRatioUnder = 1,
    IsAmmoRatioUp = 2,
    IsAmmoCount = 3,
    IsAmmoCountUnder = 4,
    IsAmmoCountUp = 5,
    IsShooterCount = 6,
    IsShooterUnder = 7,
    IsShooterUp = 8,
    IsSameSqaudCount = 9,
    IsSameSqaudUnder = 10,
    IsSameSqaudUp = 11,
    IsHpRatioUnder = 12,
    IsHpRatioUp = 13,
    IsStun = 14,
    IsFunctionBuffCheck = 15,
    IsFunctionDebuffCheck = 16,
    IsForcedStop = 17,
    IsFunctionOn = 18,
    IsFullCount = 19,
    IsFunctionCount = 20,
    IsBurstStepState = 21,
    AlwaysRecursive = 22,
    IsUseAmmo = 23,
    IsPhase = 24,
    IsPhaseUp = 25,
    IsPhaseUnder = 26,
    IsBurstSkillStep = 27,
    IsCheckMonster = 28,
    IsCover = 29,
    IsSearchElementId = 30,
    IsWeaponType = 31,
    IsClassType = 32,
    IsCheckTarget = 33,
    IsCheckDebuff = 34,
    IsHaveDecoy = 35,
    IsFullCharge = 36,
    IsHaveBarrier = 37,
    IsBurstMember = 38,
    IsNotBurstMember = 39,
    IsHighHpValue = 40,
    IsNotHaveBarrier = 41,
    IsExplosiveCircuitOff = 42,
    IsAlive = 43,
    IsHighMaxHpValue = 44,
    IsFunctionOff = 45,
    IsCheckFunctionOverlapUp = 46,
    IsCheckPartsId = 47,
    IsCheckPosition = 48,
    IsCheckMonsterType = 49,
    IsCheckTeamBurstNextStep = 50,
    IsNotCheckTeamBurstNextStep = 51,
    IsCharacter = 52,
    IsFunctionTypeOffCheck = 53,
    IsCheckEnemyNikke = 54,
    IsBurstStepCheck = 55,
    IsCheckMonsterExcludeNoneType = 56,
    IsNotHaveCover = 57,
    IsHaveCover = 58,
    IsSameSqaud = 59,
    IsCheckGradeUnder = 60,
    IsCheckCharacter = 61,
    IsCheckNotTarget = 62,
    IsCheckFunctionOverlap = 63,
    IsFirstBurstMember = 64,
    IsNotFirstBurstMember = 65,
    IsCharging = 66
}
